apiVersion: 1
policies:
  - orgId: 1
    receiver: default-email
    group_by: ['alertname']
    routes:
      - receiver: default-email
        object_matchers:
          - [severity, '=', critical]
        continue: false
