# Example configuration file for Home Network Monitoring
# Copy to config/config.yaml and edit values as needed.

influx:
  url: "http://influxdb:8086"
  org: "home-net"
  bucket: "network_metrics"
  token: "supersecrettoken"

devices:
  unifi:
    controller: "https://192.168.1.1:8443"
    username: "admin"
    password: "password"
  mikrotik:
    host: "192.168.1.2"
    username: "admin"
    password: "password"

polling:
  interval: 60
