name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      influxdb:
        image: influxdb:2.7
        ports: ["8086:8086"]
        env:
          DOCKER_INFLUXDB_INIT_MODE: setup
          DOCKER_INFLUXDB_INIT_USERNAME: admin
          DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
          DOCKER_INFLUXDB_INIT_ORG: home-net
          DOCKER_INFLUXDB_INIT_BUCKET: network_metrics
          DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: supersecrettoken
      grafana:
        image: grafana/grafana:10.3.1
        ports: ["3000:3000"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r poller/requirements.txt -r requirements-dev.txt
      - name: Run tests
        run: pytest --cov=poller --cov-report=xml
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
